#!/usr/bin/env python3
"""Build or validate the hash-locked release-validation toolchain."""

from __future__ import annotations

import argparse
import hashlib
import re
import subprocess
import sys
import tempfile
import zipfile
from collections import defaultdict
from email.parser import Parser
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REQUIREMENTS_IN = ROOT / "requirements" / "release-tools.in"
LOCK = ROOT / "requirements" / "release-tools.txt"
ANSIBLE_LOCK = ROOT / "deploy" / "ansible" / "requirements.txt"
PYTHON_VERSION = "3.14"
LINUX_X86_64_PLATFORMS = (
    "manylinux_2_28_x86_64",
    "manylinux_2_17_x86_64",
    "manylinux2014_x86_64",
)
REQUIREMENT_RE = re.compile(r"^([A-Za-z0-9_.-]+)==([^\s\\]+)(?:\s+\\)?$")
HASH_RE = re.compile(r"^\s+--hash=sha256:([0-9a-f]{64})(?:\s+\\)?$")


def canonical_name(value: str) -> str:
    return re.sub(r"[-_.]+", "-", value).lower()


def run(command: list[str]) -> None:
    subprocess.run(command, cwd=ROOT, check=True)


def read_regular(path: Path, label: str) -> str:
    if path.is_symlink() or not path.is_file():
        raise RuntimeError(f"{label} must be a regular non-symlinked file: {path}")
    try:
        return path.read_text(encoding="utf-8", errors="strict")
    except UnicodeDecodeError as error:
        raise RuntimeError(f"{label} must be valid UTF-8: {path}") from error


def direct_requirements(content: str) -> dict[str, str]:
    result: dict[str, str] = {}
    for line_number, line in enumerate(content.splitlines(), start=1):
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        match = REQUIREMENT_RE.fullmatch(stripped)
        if not match:
            raise RuntimeError(
                f"release tool requirement is not exactly pinned on line {line_number}: "
                f"{stripped}"
            )
        name = canonical_name(match.group(1))
        if name in result:
            raise RuntimeError(f"duplicate direct release tool requirement: {name}")
        result[name] = match.group(2)
    if not result:
        raise RuntimeError("release tool input contains no exact requirements")
    return result


def wheel_identity(path: Path) -> tuple[str, str]:
    with zipfile.ZipFile(path) as wheel:
        metadata_files = [
            member
            for member in wheel.namelist()
            if member.endswith(".dist-info/METADATA") and member.count("/") == 1
        ]
        if len(metadata_files) != 1:
            raise RuntimeError(f"wheel has an ambiguous METADATA record: {path.name}")
        metadata = Parser().parsestr(
            wheel.read(metadata_files[0]).decode("utf-8", errors="strict")
        )
    name = metadata.get("Name")
    version = metadata.get("Version")
    if not name or not version:
        raise RuntimeError(f"wheel is missing Name or Version metadata: {path.name}")
    return canonical_name(name), version


def download_wheels(destination: Path) -> None:
    abi = "cp" + PYTHON_VERSION.replace(".", "")
    command = [
        sys.executable,
        "-m",
        "pip",
        "download",
        "--quiet",
        "--disable-pip-version-check",
        "--no-input",
        "--only-binary=:all:",
        "--implementation=cp",
        f"--python-version={PYTHON_VERSION}",
        f"--abi={abi}",
        f"--dest={destination}",
    ]
    for platform in LINUX_X86_64_PLATFORMS:
        command.append(f"--platform={platform}")
    command.extend(("-r", str(REQUIREMENTS_IN)))
    run(command)


def collect_wheels(wheelhouse: Path) -> dict[tuple[str, str], set[str]]:
    wheels = sorted(wheelhouse.glob("*.whl"))
    if not wheels:
        raise RuntimeError("release tool resolution downloaded no wheels")
    packages: dict[tuple[str, str], set[str]] = defaultdict(set)
    names: dict[str, str] = {}
    for wheel in wheels:
        identity = wheel_identity(wheel)
        prior_version = names.setdefault(identity[0], identity[1])
        if prior_version != identity[1]:
            raise RuntimeError(
                f"resolver selected multiple versions of {identity[0]}: "
                f"{prior_version}, {identity[1]}"
            )
        packages[identity].add(hashlib.sha256(wheel.read_bytes()).hexdigest())
    return packages


def render_lock(packages: dict[tuple[str, str], set[str]]) -> str:
    lines = [
        "#",
        "# Generated by scripts/compile-release-tools-lock.py from release-tools.in.",
        "# Approved artifact scope: CPython 3.14 on Linux x86_64, binary wheels only.",
        "# Install with --require-hashes and --only-binary=:all:.",
        "#",
    ]
    for (name, version), hashes in sorted(packages.items()):
        if not hashes:
            raise RuntimeError(f"no artifact hash collected for {name}=={version}")
        lines.append(f"{name}=={version} \\")
        for index, digest in enumerate(sorted(hashes)):
            continuation = " \\" if index + 1 < len(hashes) else ""
            lines.append(f"    --hash=sha256:{digest}{continuation}")
    return "\n".join(lines) + "\n"


def parse_lock(content: str, label: str) -> dict[str, str]:
    versions: dict[str, str] = {}
    hashes: dict[str, set[str]] = defaultdict(set)
    active_name: str | None = None
    for line in content.splitlines():
        match = REQUIREMENT_RE.fullmatch(line)
        if match:
            name = canonical_name(match.group(1))
            if name in versions:
                raise RuntimeError(f"{label} contains duplicate package: {name}")
            versions[name] = match.group(2)
            active_name = name
            continue
        hash_match = HASH_RE.fullmatch(line)
        if hash_match:
            if active_name is None:
                raise RuntimeError(f"{label} contains an artifact hash before a package")
            digest = hash_match.group(1)
            if digest in hashes[active_name]:
                raise RuntimeError(f"{label} duplicates a hash for {active_name}")
            hashes[active_name].add(digest)
            continue
        stripped = line.strip()
        if stripped and not stripped.startswith("#"):
            raise RuntimeError(f"{label} contains unsupported active syntax: {line}")
    if not versions:
        raise RuntimeError(f"{label} contains no exact requirements")
    for name, version in versions.items():
        if not hashes[name]:
            raise RuntimeError(f"{label} does not hash-lock {name}=={version}")
    return versions


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.is_symlink() or (path.exists() and not path.is_file()):
        raise RuntimeError(f"refusing to replace unsafe release tools lock: {path}")
    temporary_name: str | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            newline="\n",
            dir=path.parent,
            prefix=path.name + ".",
            suffix=".tmp",
            delete=False,
        ) as temporary:
            temporary.write(content)
            temporary_name = temporary.name
        Path(temporary_name).replace(path)
    finally:
        if temporary_name:
            Path(temporary_name).unlink(missing_ok=True)


def check_lock() -> None:
    direct = direct_requirements(read_regular(REQUIREMENTS_IN, "release tool input"))
    content = read_regular(LOCK, "release tools lock")
    if "Approved artifact scope: CPython 3.14 on Linux x86_64" not in content:
        raise RuntimeError("release tools lock does not declare its artifact scope")
    root_forms = {str(ROOT), ROOT.as_posix()}
    if any(root in content for root in root_forms):
        raise RuntimeError("release tools lock contains a machine-specific path")
    locked = parse_lock(content, "release tools lock")
    for name, version in direct.items():
        if locked.get(name) != version:
            raise RuntimeError(f"direct release tool pin is missing: {name}=={version}")

    ansible = parse_lock(read_regular(ANSIBLE_LOCK, "Ansible lock"), "Ansible lock")
    conflicts = [
        f"{name}: release={version}, ansible={ansible[name]}"
        for name, version in sorted(locked.items())
        if name in ansible and ansible[name] != version
    ]
    if conflicts:
        raise RuntimeError(
            "release and Ansible locks select conflicting shared packages: "
            + "; ".join(conflicts)
        )
    print(
        f"Release tools lock valid: {len(locked)} exact, hash-verified packages; "
        f"shared_with_ansible={len(set(locked) & set(ansible))}"
    )


def generate_lock() -> None:
    direct = direct_requirements(read_regular(REQUIREMENTS_IN, "release tool input"))
    with tempfile.TemporaryDirectory(prefix="archiveweaver-release-tools-") as temporary:
        wheelhouse = Path(temporary)
        download_wheels(wheelhouse)
        packages = collect_wheels(wheelhouse)
    resolved = {name: version for name, version in packages}
    for name, version in direct.items():
        if resolved.get(name) != version:
            raise RuntimeError(f"resolver omitted direct release tool: {name}=={version}")
    atomic_write(LOCK, render_lock(packages))
    check_lock()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="validate the checked-in lock without contacting package indexes",
    )
    arguments = parser.parse_args()
    try:
        if arguments.check:
            check_lock()
        else:
            generate_lock()
    except (OSError, RuntimeError, subprocess.CalledProcessError) as error:
        print(f"Release tools lock error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
