apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: archiveweaver
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml
secretGenerator:
  - name: paperless-ngx-secrets
    envs:
      - paperless.env
  - name: paperless-postgres-ca
    files:
      - ca.pem=postgres-ca.pem
generatorOptions:
  labels:
    app.kubernetes.io/name: paperless-ngx
    app.kubernetes.io/part-of: paperless-ngx
